Get documents as compressed file
hiqdev/hipanel-module-document pull request #14
Opened 2021-06-24 08:25 UTC by bladeroot

2021-06-24 09:29 UTC, hiqsol commented
Я не понял почему надо выводить предупреждение?
Кнопки балковых действий просто не должны нажиматься пока не выбраны объекты!
@tafid что скажешь?

2021-06-24 11:24 UTC, tafid requested changes

2021-06-24 11:24 UTC, tafid commented on src/views/document/index.php
> +        <?= Html::a(Yii::t('hipanel:document', 'Get documents as compressed file'), Url::to(array_merge(['archive'], Yii::$app->request->get())), array_filter([
думаю тут нужно сделать не ссылку а конпку

2021-06-24 15:34 UTC, tafid commented on src/views/document/index.php
> +        <?= Html::a(Yii::t('hipanel:document', 'Get documents as compressed file'), Url::to(array_merge(['archive'], Yii::$app->request->get())), array_filter([
стоп, но это же не балковые кнопки, все, снимаю вопрос

2021-06-24 15:35 UTC, tafid approved these changes

2021-06-25 06:45 UTC, strorch approved these changes

2021-06-25 07:09 UTC, bladeroot commented
Nen

> Я не понял почему надо выводить предупреждение?
> Кнопки балковых действий просто не должны нажиматься пока не выбраны объекты!
> @tafid что скажешь?

Оно так потому, что выдает сжатый файл, если задействован тригер. к балку оно особо и не относится.

2021-06-25 07:11 UTC, hiqsol commented
А почему эта кнопка не в балковых действиях?!!

2021-06-25 07:14 UTC, bladeroot commented
> А почему эта кнопка не в балковых действиях?!!

Потому что они хотели получать файлом все доки, которые получили при использования фильтра. Могу сделать еще и балковую кнопочку с другим экшеном

2021-06-25 07:24 UTC, hiqsol commented
> Потому что они хотели получать файлом все доки, которые получили при использования фильтра. Могу сделать еще и балковую кнопочку с другим экшеном

тогда ок, пусть будет

2021-06-25 07:24 UTC, merged